/* Browser controller. The application reads stored evidence and estimates costs locally. */
(function(){
'use strict';
const $=id=>document.getElementById(id), A=window.NpuDemoData, W=window.NpuWorkbench;
const D=JSON.parse($('npuloop-data').textContent), state={view:'studies',tab:'summary',model:'cust_vit',preset:'edge-10tops-strict',overrides:{},node:null,researchModel:'cust_vit',scheme:'npu-default',experiment:'e9_customer_intake',recordModel:'all',recordPage:0};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finite=v=>typeof v==='number'&&Number.isFinite(v), n=(v,d=0)=>finite(v)?v.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—', pct=(v,d=1)=>finite(v)?n(v*100,d)+'%':'—', pp=(v,d=2)=>finite(v)?(v>0?'+':'')+n(v*100,d)+'%p':'—';
const compact=v=>!finite(v)?'—':v>=1e6?n(v/1e6,2)+'M':v>=1e3?n(v/1e3,1)+'K':n(v);
const ml=m=>A.MODEL_LABELS[m]||({espcn_x2:'ESPCN ×2'})[m]||m;
const badge=(text,kind='neutral')=>`<span class="badge ${kind}">${esc(text)}</span>`;
const keyValue=(label,value,mono=false)=>`<div><dt>${esc(label)}</dt><dd${mono?' class="mono"':''}>${esc(value)}</dd></div>`;
const metric=(label,value,note,tone='',unit='')=>`<div class="metric ${tone}"><div class="metric-label">${esc(label)}</div><div class="metric-value">${esc(value)}${unit?`<span class="unit">${esc(unit)}</span>`:''}</div><div class="metric-note">${esc(note)}</div></div>`;
let current=null,researchResult=null,recordData=null,recordFilename='record.json',toastTimer;
const boundLabels={compute:'연산',memory:'메모리',vector:'벡터',fallback:'호스트',none:'구조·융합'};
function error(e){$('error-banner').hidden=false;$('error-banner').textContent=e.message||String(e);console.error(e);}
function run(fn){try{$('error-banner').hidden=true;return fn();}catch(e){error(e);}}
function fill(select,items,value){select.innerHTML=items.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('');if(items.some(x=>x[0]===value))select.value=value;}
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3000);}
function download(name,data,type='application/json'){
 const body=type==='application/json'?JSON.stringify(data,null,2):data;
 const blob=new Blob([body],{type:type+';charset=utf-8'}), url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notify(name+' 저장');
}
function showRecord(title,data,filename){recordData=data;recordFilename=filename||'npuloop_record.json';$('record-title').textContent=title;$('record-json').textContent=JSON.stringify(data,null,2);$('record-dialog').showModal();}
function unit(row){return row.bound==='fallback'?'host':row.onArray?'array':row.kind==='dwconv'?'depthwise':row.cycles>0?'vector':'structural';}
function bars(result){return result.units.map(g=>`<div class="bar-row"><span class="bar-label"><i class="dot ${g.key==='host'?'amber':g.key==='array'?'blue':g.key==='depthwise'?'green':'slate'}"></i>${esc(g.label)}</span><div class="bar-track"><div class="bar-fill ${g.key}" style="width:${result.estimate.total?g.cycles/result.estimate.total*100:0}%"></div></div><span class="bar-value">${pct(g.cycles/result.estimate.total,1)}</span></div>`).join('');}
function refreshAnalysis(){
 current=W.analysis(D,state.model,state.preset,state.overrides);
 $('model-meta').innerHTML=`<div>그래프 파라미터<b>${n(current.params)}</b></div><div>MACs<b>${compact(current.estimate.totalMacs)}</b></div><div>입력<b>3 × ${current.config.img||32} × ${current.config.img||32}</b></div>`;
 $('config-state').textContent=current.custom?'사용자 설정':'기본 프리셋';
 if(!current.estimate.rows.some(x=>x.name===state.node))state.node=current.estimate.rows.filter(x=>x.cycles>0).sort((a,b)=>b.cycles-a.cycles)[0]?.name||null;
 renderSummary();renderOperators();renderComparison();renderSettings();
}
function renderSummary(){
 const r=current,host=r.operators.filter(x=>x.host),saved=r.recordedComparison;
 const support=host.length?`<div class="decision"><div class="decision-icon">!</div><div><h2>호스트 처리 필요</h2><p>${n(r.hostCount)}개 노드가 선택한 가상 NPU의 지원 범위 밖에 있습니다.</p></div></div>`:`<div class="decision good"><div class="decision-icon">✓</div><div><h2>미지원 연산 없음</h2><p>선택한 가상 NPU 프리셋의 지원 연산 범위에 해당합니다.</p></div></div>`;
 const opRows=(host.length?host:r.operators.filter(x=>x.cycles>0).slice(0,3)).map(o=>`<tr><td>${esc(o.op)}</td><td class="num">${n(o.count)}</td><td class="num">${n(o.cycles)}</td><td>${badge(o.host?'호스트':'지원',o.host?'amber':'green')}</td></tr>`).join('');
 const compare=saved?`<div class="panel callout-strip"><div class="callout-copy"><span class="overline">RECORDED COMPARISON · E9</span><h3>GELU → ReLU · 추가 학습 3 epoch</h3><p>같은 모델·프리셋의 변경 전후 기록</p></div><div class="compact-results"><div>추정 사이클 감소<strong>${pct(saved.after.saving,1)}</strong></div><div>정수 정확도 변화 · 2,000장<strong>${pp(saved.after.intAccuracy-saved.intAccuracy)}</strong></div></div><button class="btn secondary" data-go-tab="comparison">변경 비교 <span aria-hidden="true">→</span></button></div>`:`<div class="panel callout-strip"><div class="callout-copy"><span class="overline">RECORDED COMPARISON</span><h3>${r.custom?'사용자 설정의 변경 후 실험 기록 없음':'선택한 조건의 변경 후 실험 기록 없음'}</h3><p>다른 조건의 측정값으로 대체하지 않습니다.</p></div><button class="btn secondary" data-go-tab="operators">연산자 상세 →</button></div>`;
 $('analysis-summary').innerHTML=`<div class="metric-grid">${metric('총 추정 사이클',n(r.estimate.total),'해석적 비용 모델 · 호스트 비용 포함')}${metric('호스트 비용 비중',pct(r.hostShare),'총 추정 사이클 대비',r.hostCount?'amber':'')}${metric('미지원 노드',n(r.hostCount),'선택한 가상 NPU 지원 조건',r.hostCount?'amber':'','개')}${metric('MAC 배열 활용률',pct(r.estimate.util),'배열 MACs / 이론상 최대 처리량')}</div><div class="two-columns"><div class="panel"><div class="panel-head"><div><h2>실행 경로별 비용</h2><p>선택한 모델 · ${esc(r.preset)}</p></div>${badge('추정','blue')}</div><div class="bar-list">${bars(r)}</div><div class="panel-foot">${n(r.spec.pe_rows)} × ${n(r.spec.pe_cols)} PE · ${n(r.spec.cores)} cores · ${n(r.spec.freq_mhz)} MHz · DRAM ${n(r.spec.dram_gbps,1)} GB/s</div></div><div class="panel">${support}<div class="support-scroll"><table class="support-table"><thead><tr><th>연산자</th><th class="num">노드</th><th class="num">추정 사이클</th><th>상태</th></tr></thead><tbody>${opRows}</tbody></table></div><div class="panel-foot">지원 여부는 프리셋 정의 기준이며 실제 칩의 실행 결과가 아닙니다.</div></div></div>${compare}<div class="section-heading"><div><h2>상위 비용 노드</h2><p>추정 사이클 내림차순</p></div><button class="btn subtle" data-go-tab="operators">전체 노드 →</button></div><div class="panel table-container"><table><thead><tr><th>노드</th><th>연산자</th><th>실행 경로</th><th class="num">추정 사이클</th><th class="num">비중</th></tr></thead><tbody>${r.estimate.rows.filter(x=>x.cycles>0).sort((a,b)=>b.cycles-a.cycles).slice(0,4).map(row=>`<tr><td><button class="row-action mono" data-select-node="${esc(row.name)}">${esc(row.name)}</button></td><td class="mono">${esc(row.op)}</td><td>${badge(W.UNIT_LABELS[unit(row)],unit(row)==='host'?'amber':'neutral')}</td><td class="num">${n(row.cycles)}</td><td class="num">${pct(row.cycles/r.estimate.total)}</td></tr>`).join('')}</tbody></table></div>`;
}
function filteredOperators(){const q=$('operator-search').value.toLowerCase(), filter=$('operator-filter').value,sort=$('operator-sort').value;let rows=current.estimate.rows.map((r,i)=>({...r,graphIndex:i})).filter(r=>(r.name+' '+r.op+' '+r.kind).toLowerCase().includes(q));if(filter!=='all')rows=rows.filter(r=>filter==='vector'?['vector','structural','depthwise'].includes(unit(r)):unit(r)===filter);if(sort==='cycles')rows.sort((a,b)=>b.cycles-a.cycles);else if(sort==='name')rows.sort((a,b)=>a.name.localeCompare(b.name));return rows;}
function renderOperators(){
 const rows=filteredOperators();$('operator-count').textContent=`${rows.length} / ${current.estimate.rows.length}개 노드`;
 $('operator-table').innerHTML=rows.length?`<table><thead><tr><th>노드</th><th>연산자</th><th>제약</th><th class="num">추정 사이클</th><th class="num">비중</th></tr></thead><tbody>${rows.map(r=>`<tr class="selectable ${r.name===state.node?'selected':''}" data-node="${esc(r.name)}"><td><button class="row-action mono" data-select-node="${esc(r.name)}">${esc(r.name)}</button></td><td class="mono">${esc(r.kind)}</td><td>${badge(boundLabels[r.bound]||r.bound,r.bound==='fallback'?'amber':'neutral')}</td><td class="num">${n(r.cycles,r.cycles%1?1:0)}</td><td class="num">${pct(r.cycles/current.estimate.total)}<span class="mini-bar ${unit(r)}"><i style="width:${Math.min(100,r.cycles/current.estimate.total*100)}%"></i></span></td></tr>`).join('')}</tbody></table>`:'<div class="empty-state"><h2>일치하는 노드 없음</h2><p>현재 검색어와 실행 경로 필터에 해당하는 노드가 없습니다.</p></div>';
 renderInspector();
}
function renderInspector(){
 const row=current.estimate.rows.find(r=>r.name===state.node),layer=D.models[state.model].layers.find(r=>r.name===state.node);
 if(!row||!layer){$('operator-inspector').innerHTML='<span class="muted">선택한 노드 없음</span>';return;}
 const downstream=D.models[state.model].layers.filter(r=>r.inputs.includes(row.name));
 $('operator-inspector').innerHTML=`<span class="overline">NODE INSPECTOR</span><h3>${esc(row.name)}</h3><dl class="property-list">${keyValue('연산자',row.op,true)}${keyValue('실행 경로',W.UNIT_LABELS[unit(row)])}${keyValue('추정 사이클',n(row.cycles,2),true)}${keyValue('MACs',n(row.macs),true)}${keyValue('DRAM 전송량',n(row.dramB)+' B',true)}${keyValue('출력 원소',n(layer.elements),true)}${row.m&&row.k&&row.n?keyValue('GEMM M × K × N',`${row.m} × ${row.k} × ${row.n}`,true):''}</dl><p class="inspector-subtitle">입력 노드</p><div class="node-links">${layer.inputs.length?layer.inputs.map(x=>`<button data-select-node="${esc(x)}">${esc(x)}</button>`).join(''):'<span class="muted">없음</span>'}</div><p class="inspector-subtitle">출력 연결</p><div class="node-links">${downstream.length?downstream.map(x=>`<button data-select-node="${esc(x.name)}">${esc(x.name)}</button>`).join(''):'<span class="muted">없음</span>'}</div><p class="footnote">그래프 구조와 비용 모델에서 계산한 값입니다.</p>`;
}
function renderComparison(){
 const r=current,c=r.recordedComparison,host=c?.after.remainingHostOps;
 if(!c){$('analysis-comparison').innerHTML=`<div class="empty-state"><h2>변경 후 실험 기록 없음</h2><p>${r.custom?'사용자 비용 설정은 저장된 E9 변경 실험의 조건과 다릅니다.':'선택한 모델·프리셋 조합의 변경 후 평가가 저장되어 있지 않습니다.'} 비용 추정과 정확도 개선값을 임의로 생성하지 않습니다.</p><button class="btn secondary" data-action="default-comparison">ViT · strict 기록</button></div>`;return;}
 const verdict=c.after.fullySupported===null?'변경 후 지원 범위 미확인':c.after.fullySupported?'변경 후 미지원 연산 없음':'변경 후에도 호스트 처리 필요';
 const version=(after)=>{const x=after?c.after:c;return `<div class="panel padded"><div class="version-title"><h2><span class="version-marker ${after?'after':''}">${after?'B':'A'}</span>${after?'변경 모델':'기준 모델'}</h2>${badge(after?'ReLU':'GELU',after?'blue':'neutral')}</div><span class="version-caption">총 추정 사이클</span><div class="version-value">${n(x.cycles)}</div><div class="comparison-bar ${after?'after':''}"><i style="width:${x.cycles/c.cycles*100}%"></i></div><dl class="property-list">${keyValue('추가 학습',after?'3 epoch':'—')}${keyValue('FP32 정확도 · 10,000장',pct(x.floatAccuracy,2),true)}${keyValue('정수 정확도',pct(x.intAccuracy,2),true)}${keyValue('정수 평가 표본',n(x.intImages)+'장',true)}</dl></div>`;};
 $('analysis-comparison').innerHTML=`<div class="comparison-header"><div><h2>활성함수 변경 전후</h2><p>${esc(c.label)} · ${esc(c.preset)} · GELU → ReLU</p></div><button class="btn secondary" data-source="e9_customer_intake" data-model="cust_vit">E9 원본 기록</button></div><div class="comparison-grid">${version(false)}${version(true)}</div><div class="savings-banner"><span>추정 사이클 감소율</span><strong>${pct(c.after.saving,2)}</strong><span>정수 정확도 변화 ${pp(c.after.intAccuracy-c.intAccuracy)}</span></div><div class="panel"><div class="decision ${c.after.fullySupported?'good':''}"><div class="decision-icon">${c.after.fullySupported?'✓':'!'}</div><div><h2>${verdict}</h2><p>${host?.length?host.map(o=>`${o.op} ${o.count}개`).join(' · '):c.after.fullySupported?'선택한 프리셋의 지원 연산 정의에 포함됩니다.':'해당 변경의 지원 연산 정보가 없습니다.'}</p></div></div><div class="padded"><h3>분석 결론</h3><p class="footnote">${c.after.fullySupported?'지원형 프리셋에서는 원래 활성함수도 LUT로 처리됩니다. 따라서 활성함수 변경의 추정 비용 절감은 제한적입니다.':'활성함수 변경으로 GELU의 호스트 비용은 제거되지만, LayerNorm과 softmax는 남습니다. 해당 연산의 지원 여부와 모델 구조 변경 가능성을 별도로 검토해야 합니다.'}</p><p class="footnote">사이클은 가상 NPU 추정값입니다. 정확도는 저장된 E9 평가값이며, 이 화면에서 추가 학습이나 칩 실행을 수행하지 않습니다. FP32는 10,000장, 정수 경로는 ${n(c.intImages)}장으로 평가 범위가 다릅니다. 두 경로의 원시 정확도를 직접 빼지 않습니다. ${n(c.intImages)}장 표본의 정수 정확도는 E15의 전체 시험셋 결과와 구분합니다.</p></div></div>`;
}
function renderSettings(){const s=current.spec;$('setting-array').value=s.pe_rows;$('setting-cores').value=s.cores;$('setting-dram').value=s.dram_gbps;$('setting-depthwise').value=s.dw_lanes>0?'yes':'no';$('setting-activation').value=s.lut_acts.includes('gelu')?'lut':'fallback';$('settings-result').innerHTML=`<div class="panel"><div class="settings-result-metric"><span>현재 총 추정 사이클</span><strong>${n(current.estimate.total)}</strong></div><div class="settings-result-metric"><span>MAC 배열 활용률</span><strong>${pct(current.estimate.util)}</strong></div><div class="settings-result-metric"><span>호스트 처리 노드</span><strong>${n(current.hostCount)}</strong></div></div><p class="footnote">${current.custom?'사용자 설정 적용 중':'기본 프리셋 적용 중'} · 모델별 측정 정확도는 이 설정으로 갱신되지 않습니다.</p>`;}
function lineChart(layers){
 const w=980,h=245,L=42,R=15,T=20,B=37, xs=i=>L+i/Math.max(1,layers.length-1)*(w-L-R),ys=v=>T+(1-v/100)*(h-T-B);
 let content=[0,25,50,75,100].map(v=>`<line class="gridline" x1="${L}" x2="${w-R}" y1="${ys(v)}" y2="${ys(v)}"/><text x="${L-10}" y="${ys(v)+3}" text-anchor="end">${v}</text>`).join('');
 for(let i=0;i<=4;i++){const idx=Math.round(i/4*(layers.length-1));content+=`<text x="${xs(idx)}" y="${h-14}" text-anchor="middle">${idx}</text>`;}
 for(const [key,color] of [['mismatch_frac','var(--blue)'],['local_mismatch_frac','#c79040']]){content+=`<path class="curve" stroke="${color}" d="${layers.map((r,i)=>(i?'L':'M')+xs(i).toFixed(2)+','+ys(r[key]*100).toFixed(2)).join(' ')}"/>`;for(let i=0;i<layers.length;i++){const r=layers[i];content+=`<circle cx="${xs(i)}" cy="${ys(r[key]*100)}" r="2.3" fill="${color}"><title>${esc(r.name)} · ${key==='mismatch_frac'?'전파':'국소'} ${pct(r[key],4)}</title></circle>`;}}
 return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="그래프 순서별 국소 및 전파 불일치 비율">${content}<text x="${w-R}" y="${h-1}" text-anchor="end">그래프 노드 순서</text></svg>`;
}
function renderResearch(){
 researchResult=W.research(D,state.researchModel,state.scheme);const r=researchResult.summary,l=researchResult.layernorm;
 $('research-meta').innerHTML=`<div>데이터셋<b>${esc(r.dataset)}</b></div><div>평가 이미지<b>${n(r.images)}장</b></div><div>실험<b>E15</b></div>`;
 const contains0=r.ci95[0]<=0&&r.ci95[1]>=0;
 $('research-fidelity').innerHTML=`<div class="metric-grid research-metrics">${metric('모의 양자화 정확도',pct(r.fakeAccuracy,2),'동일 모델 · 동일 시험셋')}${metric('정수 실행 정확도',pct(r.intAccuracy,2),'C++ 정수 엔진 · 저장된 측정')}${metric('출력 정숫값 불일치',pct(r.mismatch,1),'전체 시험셋 · 출력 텐서 원소','amber')}${metric('정확도 차이',pp(r.delta),'정수 − 모의 · 대응 비교')}</div><div class="research-verdict"><strong>예측 일치율 ${pct(r.labelAgreement,2)} · 출력 정숫값 불일치 ${pct(r.mismatch,1)}</strong><p>정확도 차이의 95% 신뢰구간 [${pp(r.ci95[0])}, ${pp(r.ci95[1])}]. ${contains0?'0을 포함하며, 두 정확도의 동등성을 입증한 결과는 아닙니다.':'0을 포함하지 않습니다. 다중비교 보정 전의 개별 구간입니다.'} 정숫값은 소스 코드가 아니라 양자화된 출력 텐서의 원솟값입니다.</p></div>`;
 $('research-sample').textContent=`고정 ${n(researchResult.localImages)}장 배치 · 상단 전체 시험셋 지표와 별도`; $('fidelity-chart').innerHTML=lineChart(researchResult.layers);renderResearchTable();
 $('research-layernorm').innerHTML=l?`<div class="section-heading"><div><h2>LayerNorm 정수 산술 교체</h2><p>E16 · 정수 그래프 고정, 모의 실행 경로의 LayerNorm만 변경</p></div><button class="btn subtle" data-source="e16_ln_emulation">원본 기록</button></div><div class="panel"><div class="table-container"><table class="comparison-table"><thead><tr><th>측정 항목</th><th class="num">기준</th><th class="num">교체 후</th></tr></thead><tbody><tr><td>국소 불일치 · ${n(l.localImages)}장</td><td class="num">${pct(l.beforeLocal,2)}</td><td class="num">${pct(l.afterLocal,2)}</td></tr><tr><td>출력 불일치 · ${n(l.outputImages)}장</td><td class="num">${pct(l.beforeMismatch,1)}</td><td class="num">${pct(l.afterMismatch,1)}</td></tr></tbody></table></div><div class="research-note">LayerNorm의 국소 불일치를 제거한 뒤에도 출력 불일치는 남아 있습니다. 이 실험은 E9의 활성함수 변경·추가 학습과 별개입니다.</div></div>`:'';
 const sr=[...A.rows(D,'e17_dense_output')].sort((a,b)=>(a.conv_layers||0)-(b.conv_layers||0)||String(a.scheme).localeCompare(String(b.scheme)));
 const depths=[...new Set(sr.map(x=>x.conv_layers).filter(v=>Number.isFinite(v)))];
 const imgs=sr.length?sr[0].n_test:null;
 $('research-dense').innerHTML=`<div class="section-heading"><div><h2>초해상도 정수 출력</h2><p>E17 · ESPCN ×2 · Imagenette-128 · ${imgs==null?'':n(imgs)+'장'}${depths.length>1?' · conv '+depths.join('개와 ')+'개 두 깊이':''}</p></div><button class="btn subtle" data-source="e17_dense_output">원본 기록</button></div><div class="panel"><div class="table-container"><table><thead><tr><th class="num">conv 층수</th><th>가중치 양자화</th><th class="num">모의 PSNR</th><th class="num">정수 PSNR</th><th class="num">차이</th><th class="num">출력 불일치</th></tr></thead><tbody>${sr.map(x=>`<tr><td class="num">${Number.isFinite(x.conv_layers)?n(x.conv_layers):'—'}</td><td>${x.scheme==='npu-default'?'채널별':'텐서별'}</td><td class="num">${n(x.fake_psnr,3)} dB</td><td class="num">${n(x.int_psnr,3)} dB</td><td class="num">${n(x.int_vs_fake.delta,6)} dB</td><td class="num">${pct(x.output_codes.mismatch_frac)}</td></tr>`).join('')}</tbody></table></div><div class="research-note">이미지별 PSNR 평균과 출력 텐서 비교입니다. 출력 정숫값의 불일치율은 시각적 손상의 비율을 뜻하지 않습니다.${depths.length>1?' 두 깊이는 같은 폭 구성이며, 깊은 쪽의 FP32 PSNR이 더 낮으므로 품질 개선이 아니라 깊이 대조군입니다.':''}</div></div>`;
 const im=[...A.rows(D,'e20_imagenet_scale')].sort((a,b)=>String(a.scheme).localeCompare(String(b.scheme)));
 const imMeta=D.results?.e20_imagenet_scale?.meta||{};
 $('research-imagenet').innerHTML=im.length?`<div class="section-heading"><div><h2>ImageNet 규모 대조</h2><p>E20 · ${esc(imMeta.model||'ResNet-50')} · conv ${n(im[0].convolutions)}개 · 최대 K ${n(im[0].max_reduction_k)} · ${n(im[0].n_test)}장</p></div><button class="btn subtle" data-source="e20_imagenet_scale">원본 기록</button></div><div class="panel"><div class="table-container"><table><thead><tr><th>가중치 양자화</th><th class="num">FP32</th><th class="num">모의</th><th class="num">정수</th><th class="num">정수 − 모의</th><th class="num">top-1 일치</th><th class="num">출력 불일치</th></tr></thead><tbody>${im.map(x=>`<tr><td>${x.scheme==='npu-default'?'채널별':'텐서별'}</td><td class="num">${pct(x.float_acc,2)}</td><td class="num">${pct(x.fake_acc,2)}</td><td class="num">${pct(x.int_acc,2)}</td><td class="num">${pp(x.int_vs_fake.delta)} ± ${pct(x.int_vs_fake.se,2)}</td><td class="num">${pct(x.int_vs_fake.top1_agreement,2)}</td><td class="num">${pct(x.output_codes.mismatch_frac)}</td></tr>`).join('')}</tbody></table></div><div class="research-note">ImageNet 규모 <strong>그래프</strong>와 ImageNet <strong>가중치</strong>이지만 <strong>ImageNet 검증셋 정확도가 아닙니다</strong> — 이미지는 ${esc(imMeta.dataset||'Imagenette 시험 분할')}입니다. 따라서 top-1 절대값은 ImageNet 수치와 비교할 수 없습니다. 이 표가 재는 것은 같은 이미지에 대한 모의 실행과 정수 실행의 <strong>차이</strong>이며, 출력 불일치율 계산에는 라벨이 들어가지 않습니다.</div></div>`:'';
 $('research-other').innerHTML='<p class="footnote">모든 측정값은 results/의 저장된 실험 기록입니다. 브라우저에서 정수 추론을 새로 실행한 결과가 아닙니다.</p>';
}
function renderResearchTable(){if(!researchResult)return;const q=$('research-search').value.toLowerCase(),rows=researchResult.layers.filter(r=>(r.name+' '+r.op).toLowerCase().includes(q));$('research-row-count').textContent=rows.length+'개 노드';$('fidelity-table').innerHTML=`<table><thead><tr><th>노드</th><th>연산자</th><th class="num">국소 불일치</th><th class="num">전파 불일치</th><th class="num">국소 최대차</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="mono">${esc(r.name)}</td><td>${esc(r.op)}</td><td class="num">${pct(r.local_mismatch_frac,4)}</td><td class="num">${pct(r.mismatch_frac,4)}</td><td class="num">${n(r.local_max_abs)} LSB</td></tr>`).join('')||'<tr><td colspan="5">일치하는 노드 없음</td></tr>'}</tbody></table>`;}
const columns={
 e1_baselines:[['model','모델'],['float_acc','FP32 정확도','pct'],['macs','MACs','num'],['params','파라미터','num']],
 e2_ptq_grid:[['model','모델'],['scheme','방식'],['fake_acc','모의 정확도','pct'],['int_acc','정수 정확도','pct']],
 e3_lint_vs_drop:[['model','모델'],['kind','구분'],['scheme','방식'],['layer','계층'],['dloss','손실 변화','decimal']],
 e4_surgery:[['condition','변경 조건'],['original_fp32','원본 FP32','pct'],['modified_fp32','변경 후 FP32','pct'],['simulated_after','변경 후 모의','pct'],['int_acc','정수 정확도','pct']],
 e5_calibration:[['model','모델'],['scheme','방식'],['n','표본','num'],['seed','시드','num'],['fake_acc','모의 정확도','pct']],
 e6_pruning:[['model','모델'],['strategy','방식'],['ratio','비율','decimal'],['macs','MACs','num'],['ft_acc','재학습 정확도','pct'],['int8_acc','모의 양자화','pct']],
 e7_requant_ablation:[['model','모델'],['config','연산 구성'],['int_acc','정수 정확도','pct']],
 e8_scalesim:[['model','모델'],['rows','PE 행','num'],['total_scalesim','SCALE-Sim','num'],['total_ours','npuloop','num'],['ratio','사이클 비율','decimal']],
 e9_customer_intake:[['model','모델'],['params','파라미터','num'],['macs','MACs','num'],['float_acc','FP32 정확도','pct']],
 e10_engine_timing:[['model','모델'],['batch','배치','num'],['numpy.per_image_ms','NumPy ms/장','decimal'],['cpp.per_image_ms','C++ ms/장','decimal'],['speedup','호스트 속도비','decimal']],
 e11_tflite_crosscheck:[['rounding','반올림 구성'],['engine','엔진'],['images','이미지','num'],['output_mismatch_elems','불일치 원소','num'],['exact','비트 일치','bool']],
 e12_imagenette:[['kind','구분'],['scheme','방식'],['fp32','FP32 정확도','pct'],['fake_acc','모의 정확도','pct'],['int_acc','정수 정확도','pct']],
 e13_vela:[['net','모델'],['vela.total_cycles','Vela 사이클','num'],['npuloop.total_cycles','npuloop 사이클','num'],['cycle_ratio','사이클 비율','decimal']],
 e14_rounding_seeds:[['model','모델'],['seed','시드','num'],['rounding','반올림'],['int_acc','정수 정확도','pct'],['vs_reference.delta','기준 대비','pp']],
 e15_fidelity:[['model','모델'],['scheme','방식'],['n_test','평가 이미지','num'],['fake_acc','모의 정확도','pct'],['int_acc','정수 정확도','pct']],
 e16_ln_emulation:[['scheme','방식'],['variant','LayerNorm'],['fake_acc','모의 정확도','pct'],['output_codes.mismatch_frac','출력 불일치','pct']],
 e17_dense_output:[['model','모델'],['conv_layers','conv 층수','num'],['scheme','방식'],['fake_psnr','모의 PSNR','decimal'],['int_psnr','정수 PSNR','decimal'],['output_codes.mismatch_frac','출력 불일치','pct']],
 e18_requant_axes_seeds:[['model','모델'],['seed','시드','num'],['config','연산 구성'],['int_acc','정수 정확도','pct'],['vs_reference.delta','기준 대비','pp']],
 e19_adaround:[['model','모델'],['scheme','방식'],['fake_rtn','모의 RTN','pct'],['fake_ada','모의 AdaRound','pct'],['int_rtn','정수 RTN','pct'],['int_ada','정수 AdaRound','pct'],['flipped_frac','방향이 바뀐 가중치','pct']],
 e20_imagenet_scale:[['scheme','방식'],['convolutions','conv 층수','num'],['max_reduction_k','최대 K','num'],['float_acc','FP32','pct'],['fake_acc','모의','pct'],['int_acc','정수','pct'],['output_codes.mismatch_frac','출력 불일치','pct']]
};
function val(obj,path){return path.split('.').reduce((r,k)=>r?.[k],obj);}
function format(v,key,fmt){if(v==null)return'—';if(fmt==='pct')return pct(v,2);if(fmt==='pp')return pp(v);if(fmt==='num')return n(v);if(fmt==='decimal')return n(v,4);if(fmt==='bool')return v?'일치':'불일치';if(key==='model')return ml(v);return String(v);}
function filteredCatalog(){const q=$('experiment-search').value.toLowerCase().trim(),category=$('experiment-category').value;return W.catalog(D).filter(e=>(category==='all'||category===e.group)&&(!q||(e.id+' '+e.title+' '+e.description+' '+JSON.stringify(A.rows(D,e.key).map(r=>Object.fromEntries(Object.entries(r).filter(([,v])=>typeof v==='string'||typeof v==='number'))))).toLowerCase().includes(q)));}
function renderCatalog(){
 const list=filteredCatalog();$('catalog-count').textContent=list.length+' / '+W.catalog(D).length+'개 실험';
 if(!list.some(e=>e.key===state.experiment)){state.experiment=list[0]?.key||null;state.recordModel='all';state.recordPage=0;}
 $('experiment-list').innerHTML=list.map(e=>`<button class="experiment-item ${e.key===state.experiment?'active':''}" data-experiment="${e.key}" ${e.key===state.experiment?'aria-current="true"':''}><span class="exp-id">${e.id}</span><span><span class="exp-name">${esc(e.title)}</span><span class="exp-small" style="display:block">${esc(e.group)} · ${n(e.count)}개 기록</span></span></button>`).join('')||'<div class="empty-state"><p>검색 결과 없음</p></div>';
 renderExperiment();
}
function renderExperiment(){
 const e=W.catalog(D).find(e=>e.key===state.experiment);if(!e){$('experiment-detail').innerHTML='<div class="empty-state"><h2>일치하는 실험 없음</h2><p>현재 검색어와 분류 조건에 해당하는 기록이 없습니다.</p></div>';return;}
 const all=A.rows(D,e.key),models=[...new Set(all.map(r=>r.model).filter(Boolean))];if(!models.includes(state.recordModel))state.recordModel='all';
 const rs=all.map((r,i)=>({r,i})).filter(x=>state.recordModel==='all'||x.r.model===state.recordModel),pageCount=Math.max(1,Math.ceil(rs.length/40));state.recordPage=Math.min(state.recordPage,pageCount-1);const subset=rs.slice(state.recordPage*40,(state.recordPage+1)*40),cs=columns[e.key];
 const unique=[...new Set(all.map(r=>r.provenance))];const provenance=unique.some(x=>x?.includes('simulated'))?(unique.some(x=>x?.includes('measured'))?'측정·추정 혼합':'추정 결과'):'저장된 측정';
 $('experiment-detail').innerHTML=`<div class="panel"><div class="experiment-heading"><span class="overline">${e.id} · ${esc(e.group)}</span><h2>${esc(e.title)}</h2><p>${esc(e.description)}</p><div class="experiment-actions">${badge(provenance,provenance==='추정 결과'?'blue':'neutral')}${models.length?`<select id="record-model" aria-label="실험 기록 모델"><option value="all">전체 모델</option>${models.map(m=>`<option value="${esc(m)}" ${state.recordModel===m?'selected':''}>${esc(ml(m))}</option>`).join('')}</select>`:''}<button class="btn subtle" data-source="${e.key}">원본 JSON</button><button class="btn subtle" data-download-source="${e.key}">JSON 저장</button></div></div><div class="table-container record-table"><table><thead><tr>${cs.map(([,label,f])=>`<th${f?' class="num"':''}>${esc(label)}</th>`).join('')}<th>원본</th></tr></thead><tbody>${subset.map(({r,i})=>`<tr>${cs.map(([key,,f])=>`<td${f?' class="num"':''}>${esc(format(W.recordValue(D,e.key,i,key),key,f))}</td>`).join('')}<td><button class="row-action" data-source="${e.key}" data-record-index="${i}">상세</button></td></tr>`).join('')}</tbody></table></div><div class="panel-foot" style="display:flex;align-items:center;justify-content:space-between;gap:10px"><span>${rs.length?n(state.recordPage*40+1)+'–'+n(Math.min(rs.length,(state.recordPage+1)*40)):'0'} / ${n(rs.length)}개 기록</span><div><button class="btn subtle" data-record-page="prev" ${state.recordPage===0?'disabled':''}>이전</button><button class="btn subtle" data-record-page="next" ${state.recordPage===pageCount-1?'disabled':''}>다음</button></div></div></div><p class="footnote">${esc(e.key+'.json')} · 원본 값 유지<br>표는 주요 필드 요약입니다. 중첩된 계층별 결과, 설정, 평가 조건은 각 기록의 상세에 포함되어 있습니다.</p>`;
}
function renderResources(){
 const tfl=A.rows(D,'e11_tflite_crosscheck').filter(r=>r.exact),ss=A.rows(D,'e8_scalesim'),vela=A.rows(D,'e13_vela');
 const rows=[['모델 실험 실행기','구조 변경 · 학습 · PTQ · 정수 평가','Python에서 실제 학습. 브라우저는 실행 JSON을 읽어 동일 시험 부분집합의 결과를 비교.'],['내부 정수 경로','NumPy · C++ · 독립 실행기','동일 정수 그래프의 출력 대조. 외부 런타임 검증이나 NPU 실측과 별도.'],['TFLite 참조 커널',`${n(tfl[0]?.images)}장 · 저장된 E11`,'conv·MEAN·fully-connected 대조. depthwise·add·softmax는 이 외부 실험 범위에 포함되지 않음.'],['SCALE-Sim',`${ss.length}개 조건 · 저장된 E8`,'단일 코어·메모리 스톨 없는 dense conv/linear의 연산 사이클 대조.'],['Arm Vela',`${vela.length}개 망 · 저장된 E13`,'두 비용 추정기의 비교. 컴파일 스케줄과 하드웨어 실측 검증 아님.'],['현재 브라우저','비용 계산 · 결과 조회','저장된 모델 구조로 비용 계산. 양자화·학습·정수 추론은 실행하지 않음.'],['실제 NPU 하드웨어','미검증','모빌린트 SDK 및 실리콘에서 실행하지 않았음.']];
 $('validation-table').innerHTML=`<table><thead><tr><th>검증 항목</th><th>기록 범위</th><th>조건·제한</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 $('data-provenance').innerHTML=keyValue('연구 결과','results/*.json · '+Object.keys(D.results||{}).length+'개')+keyValue('구조 데이터',D.model_source==='architecture_config_only'?'모델 구성에서 추적':'체크포인트 구조에서 추적')+keyValue('브라우저 비용','해석적 systolic-array 모델')+keyValue('가중치 평가 수행',D.checkpoint_evaluation_performed?'수행':'미수행')+keyValue('HTML 빌드',D.built);
}
const studyUI=window.NpuStudyUI.mount(D,{showRecord,download,notify});
const viewLabels={studies:['모델 실험·경량화','태스크와 데이터에 맞춘 구조 변경, 회복 학습, 양자화 결과','모델 실험'],analysis:['NPU 모델 분석·검증','지원 연산, 추정 비용 및 모델 변경 결과','모델 분석'],research:['정수 실행 검증','동일 양자화 조건의 모의·정수 출력 비교','정수 검증'],experiments:['실험 기록','E1–E20 · 조건별 결과 및 원본 데이터','실험 기록'],resources:['재현 자료','연구 원고, 실행 환경 및 검증 범위','재현 자료']};
function setTab(tab){if(!['summary','operators','comparison','settings'].includes(tab))tab='summary';state.tab=tab;for(const b of document.querySelectorAll('[data-analysis-tab]')){const yes=b.dataset.analysisTab===tab;b.setAttribute('aria-selected',String(yes));b.tabIndex=yes?0:-1;$('analysis-'+b.dataset.analysisTab).hidden=!yes;}}
function route(){
 if(location.hash==='#main'){ $('main').focus(); return; }
 const hash=location.hash.slice(1)||'studies',parts=hash.split('/');let view=parts[0],tab=parts[1]||'summary';
 const aliases={cost:['analysis','settings'],intake:['analysis','summary'],prune:['experiments','e6_pruning'],ptq:['experiments','e2_ptq_grid'],surgery:['experiments','e4_surgery'],calib:['experiments','e5_calibration'],scalesim:['experiments','e8_scalesim'],tflite:['experiments','e11_tflite_crosscheck'],requant:['experiments','e7_requant_ablation'],timing:['experiments','e10_engine_timing'],imagenette:['experiments','e12_imagenette'],baselines:['experiments','e1_baselines'],lintvsdrop:['experiments','e3_lint_vs_drop'],method:['resources',''],validation:['resources',''],research_summary:['research','']};
 if(aliases[view])[view,tab]=aliases[view];if(!viewLabels[view])view='studies';
 const changedView=state.view!==view;state.view=view;if(changedView)window.scrollTo(0,0);for(const section of document.querySelectorAll('[data-view]'))section.hidden=section.dataset.view!==view;
 for(const nav of document.querySelectorAll('[data-nav]')){const yes=nav.dataset.nav===view;nav.classList.toggle('active',yes);if(yes)nav.setAttribute('aria-current','page');else nav.removeAttribute('aria-current');}
 const [title,description,label]=viewLabels[view];$('page-title').textContent=title;$('page-description').textContent=description;$('breadcrumb-current').textContent=label;
 $('export-report').hidden=!['analysis','research'].includes(view);$('export-report').lastChild.textContent=view==='research'?'측정 JSON 내보내기':'분석 JSON 내보내기';
 if(view==='studies')studyUI.render(parts[1]);if(view==='analysis')setTab(tab);if(view==='research')renderResearch();if(view==='experiments'){if(W.EXPERIMENTS.some(e=>e[0]===tab)){state.experiment=tab;state.recordModel='all';state.recordPage=0;}$('experiment-search').value='';$('experiment-category').value='all';renderCatalog();}if(view==='resources')renderResources();
 $('footer-context').textContent=view==='analysis'?'가상 NPU 추정 · 실리콘 실측 아님':'저장된 실험 기록 · 브라우저 재실행 아님';
}
function goTab(tab){location.hash='analysis/'+tab;if(state.tab===tab&&state.view==='analysis')setTab(tab);}
function exportAnalysis(){return{schema_version:1,model:state.model,preset:state.preset,overrides:state.overrides,provenance:'simulated',hardware_measured:false,model_source:D.model_source,checkpoint_evaluation_performed:false,estimate:current.estimate,unsupported_nodes:current.hostCount,recorded_comparison:current.recordedComparison};}
$('model-select').addEventListener('change',()=>run(()=>{state.model=$('model-select').value;state.node=null;refreshAnalysis();}));
$('preset-select').addEventListener('change',()=>run(()=>{state.preset=$('preset-select').value;state.overrides={};refreshAnalysis();}));
for(const id of ['operator-search','operator-filter','operator-sort'])$(id).addEventListener(id==='operator-search'?'input':'change',()=>run(renderOperators));
$('cost-settings').addEventListener('submit',event=>{event.preventDefault();run(()=>{const changes={array:Number($('setting-array').value),cores:Number($('setting-cores').value),dram:Number($('setting-dram').value),depthwise:$('setting-depthwise').value==='yes',activation:$('setting-activation').value};W.specWithOverrides(D.presets[state.preset],changes);state.overrides=changes;refreshAnalysis();notify('비용 설정 적용');});});
$('reset-settings').addEventListener('click',()=>run(()=>{state.overrides={};refreshAnalysis();notify('기본 프리셋 복원');}));
for(const id of ['research-model','research-scheme'])$(id).addEventListener('change',()=>run(()=>{state.researchModel=$('research-model').value;state.scheme=$('research-scheme').value;$('research-search').value='';renderResearch();}));
$('research-search').addEventListener('input',()=>run(renderResearchTable));
$('research-source').addEventListener('click',()=>run(()=>showRecord('E15 · '+ml(state.researchModel),researchResult.record,'npuloop_e15_'+state.researchModel+'_'+state.scheme+'.json')));
for(const id of ['experiment-search','experiment-category'])$(id).addEventListener(id==='experiment-search'?'input':'change',()=>run(()=>{state.recordPage=0;renderCatalog();}));
$('export-report').addEventListener('click',()=>run(()=>state.view==='analysis'?download('npuloop_'+state.model+'_analysis.json',exportAnalysis()):download('npuloop_'+state.researchModel+'_e15.json',researchResult.record)));
$('export-operators').addEventListener('click',()=>run(()=>{const cell=x=>'"'+String(x).replace(/"/g,'""').replace(/^[=+@-]/,"'$&")+'"';const rows=[['node','operator','path','simulated_cycles','macs','dram_bytes'],...filteredOperators().map(r=>[r.name,r.op,unit(r),r.cycles,r.macs,r.dramB])];download('npuloop_'+state.model+'_operators.csv','\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv');}));
$('close-dialog').addEventListener('click',()=>$('record-dialog').close());$('record-dialog').addEventListener('click',e=>{if(e.target===$('record-dialog')){$('record-dialog').close();}});$('download-record').addEventListener('click',()=>download(recordFilename,recordData));
function toggleTheme(){const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('theme-toggle').textContent=dark?'라이트 모드':'다크 모드';$('theme-toggle').setAttribute('aria-label',dark?'밝은 테마로 전환':'어두운 테마로 전환');}
$('theme-toggle').addEventListener('click',toggleTheme);$('theme-mobile').addEventListener('click',toggleTheme);
document.addEventListener('click',event=>run(()=>{
 const row=event.target.closest('tr[data-node]');
 const btn=event.target.closest('button');if(!btn){if(row){state.node=row.dataset.node;renderOperators();}return;}
 if(btn.dataset.analysisTab)goTab(btn.dataset.analysisTab);
 if(btn.dataset.goTab)goTab(btn.dataset.goTab);
 if(btn.dataset.selectNode){state.node=btn.dataset.selectNode;goTab('operators');renderOperators();}
 if(btn.dataset.action==='default-comparison'){state.model='cust_vit';state.preset='edge-10tops-strict';state.overrides={};$('model-select').value=state.model;$('preset-select').value=state.preset;refreshAnalysis();goTab('comparison');}
 if(btn.dataset.source){const key=btn.dataset.source;let data=D.results[key];if(btn.dataset.model)data=data.records.find(r=>r.model===btn.dataset.model);if(btn.dataset.recordIndex!=null)data=D.results[key].records[Number(btn.dataset.recordIndex)];showRecord(key,data,key+(btn.dataset.recordIndex!=null?'_'+btn.dataset.recordIndex:'')+'.json');}
 if(btn.dataset.downloadSource)download(btn.dataset.downloadSource+'.json',D.results[btn.dataset.downloadSource]);
 if(btn.dataset.experiment){state.experiment=btn.dataset.experiment;state.recordModel='all';state.recordPage=0;renderCatalog();}
 if(btn.dataset.recordPage){state.recordPage+=btn.dataset.recordPage==='next'?1:-1;renderExperiment();}
}));
document.addEventListener('change',e=>{if(e.target.id==='record-model')run(()=>{state.recordModel=e.target.value;state.recordPage=0;renderExperiment();});});
document.querySelector('[role=tablist]').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const tabs=[...document.querySelectorAll('[data-analysis-tab]')];let i=tabs.indexOf(document.activeElement);if(i<0)return;e.preventDefault();i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[i].focus();goTab(tabs[i].dataset.analysisTab);});
window.addEventListener('hashchange',()=>run(route));
run(()=>{
 fill($('model-select'),Object.keys(D.models).map(m=>[m,ml(m)]),state.model);fill($('preset-select'),['edge-10tops-strict','edge-10tops','tiny-1tops','pcie-80tops'].filter(k=>D.presets[k]).map(k=>[k,k]),state.preset);
 fill($('research-model'),[...new Set(A.rows(D,'e15_fidelity').map(r=>r.model))].map(m=>[m,ml(m)]),state.researchModel);
 $('nav-experiment-count').textContent=W.catalog(D).length;// 손으로 적지 않는다: 실험을 추가하면 레지스트리에서 따라온다
 refreshAnalysis();route();document.documentElement.dataset.appReady='true';
});
// Explicitly read-only test/export surface. No application state is hidden in a backend.
window.NpuWorkbenchApp={data:D,getState:()=>JSON.parse(JSON.stringify(state)),getStudy:()=>studyUI.getStudy(),getAnalysis:()=>current,getResearch:()=>researchResult,exportAnalysis};
})();
